const fs=require('fs'),path=require('path'),crypto=require('crypto'),D=require('better-sqlite3');
const root=path.resolve(__dirname,'../..'), data=path.join(root,'data/research/multi-asset');
const declaration=JSON.parse(fs.readFileSync(path.join(root,'config/research/multi-asset-diagnostic-v1.json')));
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const assets=declaration.assets, models=declaration.models, cfg=declaration.thresholds;
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function brier(rows,key){const x=rows.filter(r=>Number.isFinite(r[key]));return {n:x.length,brier:mean(x.map(r=>(r[key]-r.y)**2)),logLoss:mean(x.map(r=>{const p=Math.max(1e-9,Math.min(1-1e-9,r[key]));return-r.y*Math.log(p)-(1-r.y)*Math.log(1-p)}))}}
function bucket(rows,key,bins){return bins.map(([lo,hi])=>{const x=rows.filter(r=>r[key]>=lo&&r[key]<hi);return {from:lo,to:hi,n:x.length,p:mean(x.map(r=>r[key])),outcome:mean(x.map(r=>r.y)),brier:brier(x,key).brier}})}
function economics(rows){
  const out={all:rows.length,quoteRows:0,priceWindow:0,modelEdges:0,netPositive:0,thresholdQualified:0,thresholdNetPositive:0,bySide:{yes:0,no:0},netValues:[]};
  for(const r of rows){if(!Number.isFinite(r.yesAsk)||!Number.isFinite(r.yesBid))continue;out.quoteRows++;
    const candidates=[];const fee=p=>Math.ceil((cfg.feeRate*p*(1-p))*100-1e-10)/100;const yes={side:'yes',p:r.proxyAverage,ask:r.yesAsk};const no={side:'no',p:1-r.proxyAverage,ask:1-r.yesBid};
    for(const c of [yes,no]){const pricePoints=c.ask*100;if(pricePoints>=cfg.minContractPriceCents&&pricePoints<=cfg.maxContractPriceCents){out.priceWindow++;const gross=c.p-c.ask,net=gross-fee(c.ask)-cfg.slippageCents/100;c.gross=gross;c.net=net;candidates.push(c);if(gross*100>=cfg.minEdgeProbabilityPoints)out.modelEdges++;if(net>0)out.netPositive++;if(Math.abs(c.p-c.ask)*100>=cfg.minDivergenceProbabilityPoints){out.thresholdQualified++;if(net>0)out.thresholdNetPositive++;}out.bySide[c.side]++;out.netValues.push(net);}}
  }
  out.netCount=out.netValues.length;out.meanNet=mean(out.netValues);out.positiveRate=out.netValues.length?out.netValues.filter(x=>x>0).length/out.netValues.length:null;delete out.netValues;return out;
}
function main(){const latest=JSON.parse(fs.readFileSync(path.join(data,'latest-backtest.json'))),dir=latest.directory;const reports=[],all=[];
  for(const asset of assets){const report=JSON.parse(fs.readFileSync(path.join(dir,`${asset}-report.json`))),rows=fs.readFileSync(path.join(dir,`${asset}-forecasts.jsonl`),'utf8').trim().split(/\r?\n/).filter(Boolean).map(JSON.parse);const h=new D(path.join(data,asset,'history.sqlite'),{readonly:true});const candles=h.prepare('SELECT * FROM candles WHERE ticker=? AND end_period_ts=?');for(const r of rows){const c=candles.get(r.ticker,Math.floor(r.ts/1000));if(c){r.yesAsk=c.yes_ask_close;r.yesBid=c.yes_bid_close;}}h.close();
    const test=rows.filter(r=>r.block==='test');
    const scores=Object.fromEntries(models.map(k=>[k,brier(test,k)]));
    const gaps=Object.fromEntries(models.filter(k=>k!=='marketMidpoint').map(k=>[k,{brierDelta:scores[k].brier-scores.marketMidpoint.brier,logLossDelta:scores[k].logLoss-scores.marketMidpoint.logLoss}]));
    const result={asset,markets:report.scores.test.commonMarkets,rows:test.length,scores,gaps,
      probabilityCalibration:bucket(test,'proxyAverage',[[0,.1],[.1,.25],[.25,.4],[.4,.6],[.6,.75],[.75,.9],[.9,1.01]]),
      marketPriceCalibration:bucket(test,'marketMidpoint',[[0,.1],[.1,.25],[.25,.4],[.4,.6],[.6,.75],[.75,.9],[.9,1.01]]),economics:economics(test)};
    reports.push(result); all.push(...test.map(r=>({...r,asset})));
  }
  const combined={rows:all.length,scores:Object.fromEntries(models.map(k=>[k,brier(all,k)])),economics:economics(all)};const id=new Date().toISOString().replace(/[:.]/g,'-')+'-'+crypto.randomUUID().slice(0,8),out=path.join(data,'diagnostics',id);fs.mkdirSync(out,{recursive:true});const manifest={...declaration,runAt:new Date().toISOString(),sourceBacktest:dir,sourceSha256:hash(fs.readFileSync(path.join(dir,'report.json'))),livePromotion:false};fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({manifest,reports,combined},null,2));const lines=['# Multi-asset economic diagnosis','',manifest.rule,'','Test block only; lower Brier is better. Costs are estimated from minute candle asks, a 7% quadratic fee, and one cent slippage.','', '| Asset | Model Brier | Market Brier | Model-minus-market | Price-window rows | Net-positive rows | Threshold-qualified | Mean net edge |','|---|---:|---:|---:|---:|---:|---:|---:|'];for(const r of reports)lines.push(`| ${r.asset} | ${r.scores.proxyAverage.brier.toFixed(5)} | ${r.scores.marketMidpoint.brier.toFixed(5)} | ${(r.gaps.proxyAverage.brierDelta).toFixed(5)} | ${r.economics.netCount} | ${r.economics.netPositive} | ${r.economics.thresholdQualified} | ${(r.economics.meanNet*100).toFixed(2)} pts |`);lines.push('',`Combined model Brier: ${combined.scores.proxyAverage.brier.toFixed(5)}; market Brier: ${combined.scores.marketMidpoint.brier.toFixed(5)}.`,`Combined estimated net-positive opportunities: ${combined.economics.netPositive}/${combined.economics.netCount}; threshold-qualified: ${combined.economics.thresholdQualified}; mean net edge: ${(combined.economics.meanNet*100).toFixed(2)} points.`,'','The threshold diagnosis is descriptive on inspected data. It does not establish fill probability, live profitability, or a basis for changing thresholds.');fs.writeFileSync(path.join(out,'REPORT.md'),lines.join('\n'));fs.writeFileSync(path.join(data,'latest-diagnostic.json'),JSON.stringify({directory:out,completedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({directory:out,combined:combined.scores,economics:combined.economics},null,2));}
if(require.main===module)main();module.exports={main};
