// Stable machine-readable values for risk decisions and entry diagnostics.
const REJECTION_REASONS = Object.freeze({
  AUTHENTICATION_FAILED: 'authentication_failed',
  BALANCE_UNAVAILABLE: 'balance_unavailable',
  EDGE_BELOW_THRESHOLD: 'edge_below_threshold',
  ENTRY_CANDIDATE: 'entry_candidate',
  ENTRY_SUBMISSION_UNKNOWN: 'entry_submission_unknown',
  EQUITY_DRAWDOWN_LATCHED: 'equity_drawdown_latched',
  EQUITY_SNAPSHOT_STALE: 'equity_snapshot_stale',
  EQUITY_UNAVAILABLE: 'equity_unavailable',
  EXECUTION_FAILURES: 'execution_failures',
  EXIT_RECONCILIATION_PENDING: 'exit_reconciliation_pending',
  HISTORICAL_INDEX_NOT_LIVE: 'historical_index_not_live',
  INDEX_FEED_ERROR: 'index_feed_error',
  INDEX_FEED_MISSING: 'index_feed_missing',
  INDEX_FEED_STALE: 'index_feed_stale',
  INDEX_VOLATILITY_WARMUP: 'index_volatility_warmup',
  INSUFFICIENT_BALANCE: 'insufficient_balance',
  INVALID_BALANCE: 'invalid_balance',
  INVALID_EQUITY: 'invalid_equity',
  INVALID_PERSISTED_RISK: 'invalid_persisted_risk',
  INVALID_QUOTE: 'invalid_quote',
  INVALID_SIGNAL: 'invalid_signal',
  MAX_POSITIONS: 'max_positions',
  MINIMUM_BALANCE: 'minimum_balance',
  MISSING_INDEX_SAMPLES: 'missing_index_samples',
  MISSING_QUOTE: 'missing_quote',
  MISSING_STRIKE: 'missing_strike',
  NET_EDGE_BELOW_THRESHOLD: 'net_edge_below_threshold',
  OFFICIAL_STRIKE_REQUIRED: 'official_strike_required',
  ONE_CONTRACT_EXCEEDS_EQUITY_RISK_CAP: 'one_contract_exceeds_equity_risk_cap',
  OUTSIDE_ENTRY_WINDOW: 'outside_entry_window',
  PER_CONTRACT_CAP: 'per_contract_cap',
  PRICE_OUT_OF_RANGE: 'price_out_of_range',
  SAFETY_UNAVAILABLE: 'safety_unavailable',
  SESSION_DRAWDOWN: 'session_drawdown',
  SETTLEMENT_REFERENCE_MISSING_OR_STALE: 'settlement_reference_missing_or_stale',
  SETTLEMENT_REFERENCE_UNAVAILABLE: 'settlement_reference_unavailable',
  SIZE_BELOW_ONE_CONTRACT: 'size_below_one_contract',
  STALE_MARKET_QUOTE: 'stale_market_quote',
  STALE_QUOTE: 'stale_quote',
  STALE_SPOT_PRICE: 'stale_spot_price',
  STATE_PERSISTENCE_FAILED: 'state_persistence_failed',
  STOPPED: 'stopped',
  TICKER_EXPOSURE_CAP: 'ticker_exposure_cap',
  VOLATILITY_UNAVAILABLE: 'volatility_unavailable',
});

function rejectionLabels(config = {}) {
  return {
    [REJECTION_REASONS.OUTSIDE_ENTRY_WINDOW]: `outside minutes ${config.ENTRY_START_MINUTES ?? 0}–${config.TRADING_WINDOW ?? 4} after open / within ${config.ENTRY_CLOSE_BUFFER_SECONDS ?? 30}s of close`,
    [REJECTION_REASONS.STALE_QUOTE]: 'stale quotes', [REJECTION_REASONS.MISSING_QUOTE]: 'missing quotes', [REJECTION_REASONS.INVALID_QUOTE]: 'invalid quotes',
    [REJECTION_REASONS.MISSING_STRIKE]: 'missing strike', [REJECTION_REASONS.PRICE_OUT_OF_RANGE]: 'price outside entry limits',
    [REJECTION_REASONS.EDGE_BELOW_THRESHOLD]: 'edge below threshold', [REJECTION_REASONS.NET_EDGE_BELOW_THRESHOLD]: 'edge insufficient after costs',
    [REJECTION_REASONS.ENTRY_CANDIDATE]: 'candidate did not produce an affordable order',
    [REJECTION_REASONS.INDEX_FEED_MISSING]: 'authorized BRTI feed is not connected',
    [REJECTION_REASONS.INDEX_FEED_STALE]: 'BRTI feed is stale', [REJECTION_REASONS.INDEX_FEED_ERROR]: 'BRTI feed read failed',
    [REJECTION_REASONS.INDEX_VOLATILITY_WARMUP]: 'BRTI completed-minute history is warming up',
    [REJECTION_REASONS.MISSING_INDEX_SAMPLES]: 'settlement averaging samples are incomplete',
    [REJECTION_REASONS.OFFICIAL_STRIKE_REQUIRED]: 'official Kalshi strike metadata is missing',
    [REJECTION_REASONS.HISTORICAL_INDEX_NOT_LIVE]: 'historical index data cannot authorize live entries',
    [REJECTION_REASONS.VOLATILITY_UNAVAILABLE]: 'volatility not yet measured (warming up)',
  };
}
module.exports = { REJECTION_REASONS, rejectionLabels };
